version: '3.9'

services:

  #--------------
  # PHP SERVICE -
  #--------------
  php:
    image: ${PHP_BASE_IMAGE}:${PHP_VERSION}
    container_name: php
    tty: true
    working_dir: /var/www
    ports:
      - ${PHP_HTTP_PORT}:80
    volumes:
      - ${PHP_CODE_PATH}:/var/www
      - ./php/php.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - local-dev
  
  #---------------------
  # PHP-SWOOLE SERVICE -
  #---------------------
  php-swoole:
    image: ${PHP_SWOOLE_BASE_IMAGE}:${PHP_SWOOLE_VERSION}
    container_name: php-swoole
    tty: true
    working_dir: /var/www
    ports:
      - ${PHP_SWOOLE_HTTP_PORT}:1215
      - ${PHP_SWOOLE_GRPC_PORT}:9000
    volumes:
      - ${PHP_SWOOLE_CODE_PATH}:/var/www
      - ./php/php.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - local-dev

  #----------------
  # NGINX SERVICE -
  #----------------
  nginx:
    image: nginx:${NGINX_VERSION}
    tty: true
    container_name: nginx
    ports:
      - "${NGINX_HTTP_PORT}:80"
    volumes:
      - ${PHP_CODE_PATH}:/var/www
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/conf.d/php:/etc/nginx/conf.d
    entrypoint:
      - "nginx"
    command: ["-g", "daemon off;"]
    networks:
      - local-dev

  #----------------
  # NODEJS SERVICE -
  #----------------
  nodejs:
    image: ${NODE_BASE_IMAGE}:${NODE_VERSION}
    tty: true
    working_dir: /apps
    container_name: nodejs
    ports:
      - ${NODE_HTTP_PORT}:3000
    volumes:
      - /var/run/dbus:/var/run/dbus
      - ${NODE_PROJECTS_PATH}:/apps
      - ./supervisor/node:/etc/supervisor/conf.d
      - ./supervisor/supervisord.conf:/etc/supervisor/supervisord.conf
    networks:
      - local-dev

  #-----------------
  # GOLANG SERVICE -
  #-----------------
  golang:
    image: ${GOLANG_IMAGE}:${GOLANG_VERSION}
    container_name: golang
    tty: true
    ports:
      - ${GOLANG_GRPC_PORT}:5000
      - ${GOLANG_HTTP_PORT}:8080
    volumes:
      - ${GOLANG_PROJECT_PATH}:/go
    networks:
      - local-dev

  #----------------
  # REDIS SERVICE -
  #----------------
  redis:
    image: ${REDIS_IMAGE}:${REDIS_VERSION}
    container_name: redis
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - redis_data:/data
    networks:
      - local-dev

#----------
# NETWORK -
#----------
networks:
  local-dev:
    name: local-dev
    driver: bridge

#----------
# VOLUMES -
#----------
volumes:
  redis_data:
    driver: local