version: '3.9'

services:
  
  # PHP
  php:
    build: 
      context: .
      dockerfile: php/Dockerfile 
      args:
        uid: ${UID}
        user: ${PHP_USER}
        php_version: ${PHP_VERSION}
        composer_version: ${COMPOSER_VERSION}
    image: laravel/php:${PHP_VERSION}
    container_name: php
    tty: true
    working_dir: /var/www
    ports:
      - "8888:80"
    volumes:
      - ${CODE_PATH}:/var/www
      - ~/.ssh:/home/${USER}/.ssh
      - ./php/php.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - my-network

  # NODEJS
  nodejs:
    build:
      context: .
      dockerfile: node/Dockerfile
      args:
        USER: ${GLOBAL_USER}
        NODE_VERSION: ${NODE_VERSION}
    tty: true
    container_name: nodejs
    ports:
      - "3000:3000"
    volumes:
      - ${CODE_PATH}:/app
    networks:
      - my-network
  
  # NGINX
  nginx:
    image: nginx:${NGINX_VERSION}
    tty: true
    container_name: nginx
    ports:
      - "${NGINX_HTTP_PORT}:80"
    volumes:
      - ${CODE_PATH}:/var/www
      - ./nginx/conf.d:/etc/nginx/conf.d
    entrypoint:
      - "nginx"
    command: ["-g", "daemon off;"]
    networks:
      - my-network

  # MYSQL
  mysql:
    image: mysql:${MYSQL_VERSION}
    tty: true 
    container_name: mysql
    ports:
      - "${MYSQL_HTTP_PORT}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=${MYSQL_ALLOW_EMPTY_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MY_ROOT_PASSWORD}
    networks:
      - my-network

  # POSTGRES
  postgres:
    image: postgres:${POSTGRES_VERSION}
    tty: true
    container_name: postgres
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - my-network

  # PGADMIN
  pgadmin:
    image: dpage/pgadmin4:${PGADMIN_VERSION}
    tty: true 
    container_name: pgadmin
    ports:
      - "${PGADMIN_PORT}:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_ADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
      - PGADMIN_CONFIG_SERVER_MODE=${PGADMIN_CONFIG_SERVER_MODE}
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - my-network

  # PHPMYADMIN
  phpmyadmin:
    image: phpmyadmin:${PHP_MYADMIN_VERSION}
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: ${MY_ROOT_PASSWORD}
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - ${PHP_MY_ADMIN_PORT}:80
    networks:
      - my-network

# Network
networks:
  my-network:
    name: my-network
    driver: bridge

# Volumes
volumes:
  mysql_data:
    driver: local
  postgres_data:
    driver: local
  pgadmin_data:
    driver: local