export const Title = {
    
    "dashboard_side_search": "Search (ရှာရန်)",
    "dashboard_side_category": "Category List",
    "dashboard_side_item": "Item List",
    "dashboard_side_bidder": "Bidder’s Reg No List",

    "confirm" : "",
    "confirm_no": "မလုပ်တော့ပါ",
    "confirm_yes": "ထပ်ပေါင်းထည့်မည်",
    "user_add_confirm_yes" : "ထပ်ပေါင်းထည့်မည်",
    "user_add_confirm_no" : "မလုပ်တော့ပါ",
    "user_add_user_field_name": "Username",
    "user_add_user_success_title": "Successfully added a user. (အသုံးပြုသူ ထပ်ပေါင်းထည့်ခြင်း အောင်မြင်ပါသည်။)",
    "user_add_user_success_dialog_header": "Success (အောင်မြင်ပါသည်)",
    "dialog_alert_yes" : "OK (ဟုတ်ပြီ)",
    "user_reset_password": "Reset Password (လျှို့ဝှက်နံပါတ် ပြန်လည်သတ်မှတ်မည်)",
    "user_reset_pass_sure": "Are you sure? (သေချာပါသလား။)",
    "user_reset_pass_alert_yes": "Reset (သေချာပါသည်)",
    "user_reset_pass_body": "Are you sure to reset this password? (ဤလျှို့ဝှက်နံပါတ်ကို ပြန်လည် သတ်မှတ်ရန်သေချာပါသလား။)",
    "user_reset_pass_success_message": "Successfully reset the password. (လျှို့ဝှက်နံပါတ်ပြန်လည် သတ်မှတ်ခြင်း အောင်မြင်ပါသည်။)",
    "user_reset_pass_new_pass": "New Password (လျှို့ဝှက်နံပါတ်အသစ်)",
    "cat_header": "Category List (အမျိုးအစားများ စာရင်း)",
    "cat_add_cat_button_title": "New Category (အမျိုးအစားအသစ် ထည့်မည်)",
    "cat_add_confirm_yes": "Add (ပေါင်းထည့်မည်)",
    "cat_select_category": "Select Main Category (ပင်မအမျိုးအစား ရွေးပါ)",
    "cat_sub_cat_name_en": "Category Name - English (အမျိုးအစားအမည် - အင်္ဂလိပ်လို)",
    "cat_sub_cat_name_mm": "Category Name - Burmese (အမျိုးအစားအမည် - မြန်မာလို)",
    "item_header": "Item List (ပစ္စည်းများ စာရင်း)",
    "item_add_item_title": "New Item (ပစ္စည်းအသစ် ထည့်မည်)",
    "item_add_item_dialog_title": "Add Item (ပစ္စည်းအသစ် ထည့်ရန်)",
    "item_add_item_main_category": "Select Main Category (ပင်မအမျိုးအစား ရွေးပါ)",
    "item_add_next_title": "Next (ဆက်၍)",
    "item_add_lot_no_title": "Lot No (အတွဲအမှတ်)",
    "select_city": "Select City (မြို့ ရွေးပါ)",
    "item_available_date_select": "Available Date (ဝယ်ယူနိုင်သည့်ရက်စွဲ)",
    "item_add_sub_select_title": "Select Category (အမျိုးအစား ရွေးပါ)",
    "item_add_quantity": "Quantity (အရေအတွက်)",
    "bid_page_title": "Bidder’s Registration List (မှတ်ပုံတင်ထားသောလေလံဆွဲသူ စာရင်း)",
    "bid_add_bidder_button_title": "New (အသစ် ထည့်မည်)",
    "bid_data_table_lot": "Lot No",
    "bid_data_table_bid_reg": "Bidder Reg No",
    "bid_add_bid_title": "Add Bidder’s Reg No (လေလံဆွဲသူအသစ် ထည့်ရန်)",
    "bid_add_bid_no": "Bidder’s Registration No (မှတ်ပုံတင်ထားသော လေလံဆွဲသူ နံပါတ်)",
    "bid_add_name": "Name (အမည်)",
    "bid_add_company": "Company (ကုမ္ပဏီ)",
    "bid_add_country": "Country (နိုင်ငံ)",

    "data_table_search_not_found": "No data found",
    "data_table_name" : "Name",
    "data_table_delete": "Delete (ဖျက်မည်)",
    "data_table_company": "Company",
    "data_table_country": "Country",
    "data_table_actions": "Actions (လုပ်ဆောင်ချက်များ)",
    "data_table_download_csv": "Download CSV",

    "report_gold_coin_title": "Gold Coin (ရွှေဒင်္ဂါး စာရင်း)",

    "buyer_name": "Buyer’s Name",
    "nrc": "NRC",
    "phone": "Phone",
    "city": "City",
    "gold_coin_type": "Gold Coin Type",
    "date": "Date",
    "monthly_income": "Monthly Income (Ks)",
};