ARG PHP_VERSION=8.3
ARG COMPOSER_VERSION=latest

# composer
FROM composer:${COMPOSER_VERSION} as composer

FROM php:${PHP_VERSION}-fpm-alpine

ARG USERNAME=empc
ARG USER_UID=1000
ARG USER_GID=$USER_UID

RUN apk add --no-cache \
    zsh \
    sudo \
    git \
    php-gd \
    php-zip \ 
    librdkafka && \
    rm -rf /var/cache/apk/*

RUN set -eux; \
    apk add --no-cache --virtual .build-deps \
        $PHPIZE_DEPS \
        curl \
        gcc \
        linux-headers \
        make \
        libxml2-dev \
        libpng-dev \
        libzip-dev \
        oniguruma-dev \
        librdkafka-dev \
        && docker-php-ext-install \
            pdo_mysql \
            bcmath \
            xml \
            zip \
            gd \
            mbstring \
            exif \
            fileinfo \
            opcache \
    && pecl install swoole rdkafka redis \
    && docker-php-ext-enable swoole rdkafka redis \
    && apk del -f .build-deps \
    && rm -rf /tmp/pear ~/.pearrc

RUN adduser -D -u $USER_UID -g $USER_GID $USERNAME

COPY --from=composer /usr/bin/composer /usr/bin/composer

USER $USERNAME