ARG PHP_VERSION=8.3
ARG COMPOSER_VERSION=latest

# composer
FROM composer:${COMPOSER_VERSION} as composer

# build
FROM alpine:latest as build

RUN apk --no-cache add git && \
    rm -rf /var/cache/apk/*

WORKDIR /tmp

RUN git clone --depth=1 \
    https://github.com/ohmyzsh/ohmyzsh.git

# Main
FROM php:${PHP_VERSION}-fpm-alpine

ARG USERNAME=php
ARG USER_UID=1000
ARG USER_GID=$USER_UID

RUN apk add --no-cache \
    zsh \
    sudo \
    git \
    php-gd \
    php-zip \ 
    librdkafka \
    neovim && \
    rm -rf /var/cache/apk/*

RUN set -eux; \
    apk add --no-cache --virtual .build-deps \
        $PHPIZE_DEPS \
        curl \
        libxml2-dev \
        libpng-dev \
        libzip-dev \
        oniguruma-dev \
        librdkafka-dev \
        && docker-php-ext-install \
            pdo_mysql \
            bcmath \
            xml \
            zip \
            gd \
            mbstring \
            # openssl \
            exif \
            fileinfo \
            opcache \
            # dom \
            # xmlreader \
            # xmlwriter \
    && pecl install pcov swoole rdkafka redis grpc \
    && docker-php-ext-enable pcov swoole rdkafka redis grpc \
    && apk del -f .build-deps \
    && rm -rf /tmp/pear ~/.pearrc

RUN adduser -D -u $USER_UID -g $USER_GID $USERNAME && \
    mkdir -p /etc/sudoers.d && \
    echo "$USERNAME ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/$USERNAME

COPY --from=composer /usr/bin/composer /usr/bin/composer
COPY --from=build /tmp/ohmyzsh /home/$USERNAME/.oh-my-zsh

RUN cp /home/$USERNAME/.oh-my-zsh/templates/zshrc.zsh-template /home/$USERNAME/.zshrc && \
    sed -i 's/ZSH_THEME="robbyrussell"/ZSH_THEME="lambda"/' /home/$USERNAME/.zshrc

USER $USERNAME

SHELL ["/bin/zsh", "-c"]